/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as randomIpfsNftSol from "./RandomIpfsNFT.sol";
export type { randomIpfsNftSol };
export type { BasicNFT } from "./BasicNFT";
