/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as randomIpfsNftSol from "./RandomIpfsNFT.sol";
export { BasicNFT__factory } from "./BasicNFT__factory";
